### ISSUE TITLE
auto select Calculation Methods

### ISSUE THREAD

**Issue by syrakozz** [batoulapps/BAPrayerTimes#5]
you mention the calculation method for some country, 
could you plz provide any automtic selection for the default calculation method for the countries 
like 
Gulf >>> BAPrayerMethodFixedIsha
Moonsighting Committee Worldwide >> BAPrayerMethodMCW
...
so in that way the project will auto select the correct calculation for each country ,

**Comment by ameiralzoubi** [comment]
That is something we are working on, but it will be in a different project https://github.com/batoulapps/PrayerMethod
